# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /home
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

spring:
  thymeleaf:
    prefix: classpath:/zxyhome/htmls
    suffix: .html